static const std::array<const std::array<const DfaState, 13>, 256> STATE_TBL{
    {// character 0
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 1
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 2
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 3
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 4
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 5
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 6
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 7
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 8
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 9
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 10
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 11
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 12
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 13
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 14
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 15
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 16
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 17
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 18
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 19
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 20
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 21
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 22
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 23
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 24
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 25
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 26
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 27
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 28
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 29
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 30
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 31
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 32
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 33
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 34
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 35
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 36
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 37
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 38
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 39
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 40
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 41
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 42
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 43
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 44
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 45
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 46
     {{DfaState::Dot, DfaState::Accept, DfaState::RealInit, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 47
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 48
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 49
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 50
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 51
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 52
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 53
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 54
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 55
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 56
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 57
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 58
     {{DfaState::Colon, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 59
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 60
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 61
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Special}},
     // character 62
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 63
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 64
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 65
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 66
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 67
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 68
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 69
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 70
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 71
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 72
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 73
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 74
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 75
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 76
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 77
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 78
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 79
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 80
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 81
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 82
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 83
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 84
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 85
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 86
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 87
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 88
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 89
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 90
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 91
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 92
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 93
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 94
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 95
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 96
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 97
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 98
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 99
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 100
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 101
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 102
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 103
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 104
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 105
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 106
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 107
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 108
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 109
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 110
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 111
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 112
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 113
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 114
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 115
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 116
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 117
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 118
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 119
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 120
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 121
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 122
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 123
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 124
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 125
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 126
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 127
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 128
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 129
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 130
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 131
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 132
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 133
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 134
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 135
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 136
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 137
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 138
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 139
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 140
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 141
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 142
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 143
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 144
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 145
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 146
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 147
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 148
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 149
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 150
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 151
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 152
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 153
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 154
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 155
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 156
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 157
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 158
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 159
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 160
     {{DfaState::Whitespace, DfaState::Accept, DfaState::Accept,
       DfaState::Error, DfaState::Accept, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept, DfaState::Accept}},
     // character 161
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 162
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 163
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 164
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 165
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 166
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 167
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 168
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 169
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 170
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 171
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 172
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 173
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 174
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 175
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 176
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 177
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 178
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 179
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 180
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 181
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 182
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 183
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 184
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 185
     {{DfaState::Integer, DfaState::Letter, DfaState::Integer,
       DfaState::RealRational, DfaState::RealRational,
       DfaState::RealFirstExpDigit, DfaState::RealFirstExpDigit,
       DfaState::RealSecondExpDigit, DfaState::RealThirdExpDigit,
       DfaState::Error, DfaState::Accept, DfaState::RealRational,
       DfaState::Error}},
     // character 186
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 187
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 188
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 189
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 190
     {{DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error}},
     // character 191
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 192
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 193
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 194
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 195
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 196
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 197
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 198
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 199
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 200
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 201
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 202
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 203
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 204
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 205
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 206
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 207
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 208
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 209
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 210
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 211
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 212
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 213
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 214
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 215
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 216
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 217
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 218
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 219
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 220
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 221
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 222
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 223
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 224
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 225
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 226
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 227
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 228
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 229
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 230
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 231
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 232
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 233
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 234
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 235
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 236
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 237
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 238
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 239
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 240
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 241
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 242
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 243
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 244
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 245
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 246
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 247
     {{DfaState::Special, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Accept, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Accept, DfaState::Accept, DfaState::Error,
       DfaState::Error}},
     // character 248
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 249
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 250
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 251
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 252
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 253
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 254
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}},
     // character 255
     {{DfaState::Letter, DfaState::Letter, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Error, DfaState::Error,
       DfaState::Error, DfaState::Error, DfaState::Accept, DfaState::Accept,
       DfaState::Accept}}}};

static const std::vector<std::string> RESERVED_WORDS = {
    "and",       "array",
    "asm",       "begin",
    "break",     "case",
    "const",     "constructor",
    "continue",  "destructor",
    "div",       "do",
    "downto",    "else",
    "end",       "false",
    "file",      "for",
    "function",  "goto",
    "if",        "implementation",
    "in",        "inline",
    "interface", "label",
    "mod",       "nil",
    "not",       "object",
    "of",        "on",
    "operator",  "or",
    "packed",    "procedure",
    "program",   "record",
    "repeat",    "set",
    "shl",       "shr",
    "string",    "then",
    "to",        "true",
    "type",      "unit",
    "until",     "uses",
    "var",       "while",
    "with",      "xor"};
